apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true
    traefik: true
    gateway: true
  
  settings.yaml: |
    title: Vaclab Home
    favicon: https://raw.githubusercontent.com/vacp2p/vaclab-2/feat/add_lab_components/extras/vac-logo-light-no-bg.png
    headerStyle: clean
    theme: dark
    color: slate
    providers:
      longhorn:
        url: https://longhorn.vaclab.diarra.tech
  
  bookmarks.yaml: |
    - Documentation:
        - Kubernetes:
            - abbr: K3s
              href: https://k3s.io/
        - Vaclab 2.0 Stack:
            - abbr: vaclab-2.0-stack
              href: https://www.notion.so/Vaclab-2-0-Full-Software-Stack-2d08f96fb65c8008abfdcfe86a2c3324
        - Vaclab 2.0 Bandwidth Aware Scheduling:
            - abbr: vaclab-2.0-bw-scheduling
              href: https://www.notion.so/Vaclab-2-0-Bandwidth-Aware-Scheduling-2d08f96fb65c804eb44fdc7b75e079f9
        
    
    - Git Repositories:
        - Vaclab 2.0:
            - abbr:vaclab-2
              href: https://github.com/vacp2p/vaclab-2
        - Local Vaclab:
            - abbr: vaclab-local
              href: https://github.com/vacp2p/vaclab-2
        - Vaclab K8S Plugins:
            - abbr: vaclab-k8s-plugins
              href: https://github.com/vacp2p/vaclab-k8s-plugins
    
  
  services.yaml: |
    - Cluster Management:
        - Rancher:
            icon: rancher
            href: https://rancher.vaclab.diarra.tech
            description: Kubernetes Management Platform
            namespace: cattle-system
            podSelector: app=rancher

    - Storage:
        - Longhorn:
            icon: longhorn
            href: https://longhorn.vaclab.diarra.tech
            description: Distributed Block Storage
            namespace: longhorn-system
            podSelector: app.kubernetes.io/name=longhorn
            widget:
              type: longhorn
              provider: longhorn

    - Monitoring:
        - Grafana:
            icon: grafana
            href: https://grafana.vaclab.diarra.tech
            description: Metrics Visualization
            namespace: vmetrics
            app: grafana

        - VictoriaLogs:
            icon: victoriametrics
            href: https://vlselect.vaclab.diarra.tech
            description: Log Aggregation & Search
            namespace: victorialogs
            podSelector: app=vlselect

    - Observability:
        - Hubble UI:
            icon: cilium
            href: https://hubble.vaclab.diarra.tech
            description: Network Observability
            namespace: kube-system
            podSelector: k8s-app=hubble-ui
  
  widgets.yaml: |
    - logo:
        icon: https://raw.githubusercontent.com/vacp2p/vaclab-2/feat/add_lab_components/extras/vac-logo-light-no-bg.png
    
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Vaclab Cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    
    - resources:
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
    
    - search:
        provider: duckduckgo
        target: _blank
    
    - greeting:
        text_size: xl
        text: "Welcome to Vaclab"
    
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hour12: false
  
  docker.yaml: ""
  custom.css: ""
  custom.js: ""
